# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='question',
            new_name='lab_question',
        ),
    ]
