# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rawdata_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Submission')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Variable')),
            ],
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='variable',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
