# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20160222_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='DataValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('number_of_variables', models.IntegerField()),
                ('number_of_trials', models.IntegerField()),
                ('bigLab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.BigLab')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=20)),
                ('trials', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='datavalues',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Variable'),
        ),
    ]
