# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20160302_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.DecimalField(decimal_places=10, max_digits=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Submission')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Variable')),
            ],
        ),
    ]
