# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_biglab_number_of_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='testLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('question_prompt', models.CharField(max_length=200)),
                ('test_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testLab')),
            ],
        ),
    ]
