# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20160302_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='w_number',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 17, 31, 40, 264660, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
